# Database Configuration
database:
  host: localhost
  port: 3306
  name: mceconomy
  username: your_username
  password: your_password
  table_prefix: mcue_

# General Settings
settings:
  initial_balance: 0.0
  currency_symbol: "$"
  currency_format: "#,##0.00"
  language: en_US
  check_updates: true
  server_id: null  # Optional server identifier. Use String value
  
# Transaction Settings
transactions:
  enable_logging: true
  payment_tax: 0.0
  minimum_payment: 0.0
  maximum_payment: -1  # -1 means no limit
